// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrBhj3Q5Yh_hshDkVNZLJGyTmDmLj2Mkc',
    appId: '1:605186129716:web:d342966437401c4338af61',
    messagingSenderId: '605186129716',
    projectId: 'gen-lang-client-0325095734',
    authDomain: 'gen-lang-client-0325095734.firebaseapp.com',
    storageBucket: 'gen-lang-client-0325095734.firebasestorage.app',
    measurementId: 'G-JXJM33Q62Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWyZ2Z0W6wQq--FQUyE0rT8vbwRTqJUjA',
    appId: '1:605186129716:android:267655041a6b2cfd38af61',
    messagingSenderId: '605186129716',
    projectId: 'gen-lang-client-0325095734',
    storageBucket: 'gen-lang-client-0325095734.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq4nSm4lq6dSA1nA7tBi7Ur5Fsi0T8B9E',
    appId: '1:605186129716:ios:804f4e10bfb35cd938af61',
    messagingSenderId: '605186129716',
    projectId: 'gen-lang-client-0325095734',
    storageBucket: 'gen-lang-client-0325095734.firebasestorage.app',
    iosBundleId: 'com.example.blooket',
  );
}
